-- 코드를 입력하세요
SELECT DISTINCT B.USER_ID, B.NICKNAME,CONCAT(CONCAT(CITY,' '),CONCAT(CONCAT(STREET_ADDRESS1,' '),STREET_ADDRESS2))AS 전체주소,(SELECT SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8)
                FROM USED_GOODS_USER
                WHERE TLNO = B.TLNO AND LENGTH(TLNO) = 11) AS 전화번호
FROM USED_GOODS_BOARD A INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE B.USER_ID IN (SELECT A.WRITER_ID
                   FROM USED_GOODS_BOARD A
                   GROUP BY A.WRITER_ID
                   HAVING COUNT(A.WRITER_ID)>= 3)
ORDER BY B.USER_ID DESC